Repository fuseml/fuseml, pull requests merged in 2021-03, with the labels that each got.

#29 fix: Wait until the pod is not only 'Running' but also Ready.
  kubernetes/cluster.go
  statik/statik.go
Labels: area/bug, in progress

#31 fix: Do not run CI workflow when there's is no code change
  .github/workflows/main.yml
Labels: area/ci, in progress

#34 refactor: Do not track statik.go in git
  .gitignore
  Makefile
  statik/statik.go
Labels: area/core, in progress

#30 feat: Include inference URL to the App route
  embedded-files/serving/deployment.yaml.tmpl
  embedded-files/serving/kfserving.yaml.tmpl
  embedded-files/serving/knative.yaml.tmpl
  paas/client.go
Labels: area/core, in progress

#36 build: Add Dockerfile for MLFlow and update it to 1.14.1
  assets/images/mlflow/Dockerfile
  assets/mlflow/Chart.yaml
  embedded-files/mlflow-0.0.1.tgz
  paas/client.go
Labels: area/blueprint, area/core, in progress

#43 feat: Update tekton components to their latest version
  Makefile
  deployments/tekton.go
  embedded-files/tekton/dashboard-v0.15.0.yaml
  embedded-files/tekton/fuseml.yaml
  embedded-files/tekton/kaniko.yaml
  embedded-files/tekton/pipeline-v0.22.0.yaml
  embedded-files/tekton/pipeline.yaml
  embedded-files/tekton/triggers-v0.12.1.yaml
  embedded-files/tekton/triggers.yaml
Labels: area/core, in progress

#41 fix: Delete temporary directories after usage
  paas/client.go
Labels: area/core, in progress

#8 Serving with seldon
  .github/workflows/main.yml
  Makefile
  acceptance/acceptance_suite_test.go
  cmd/root.go
  embedded-files/serving/deployment.yaml.tmpl
  embedded-files/serving/knative.yaml.tmpl
  embedded-files/serving/seldon_mlflow.yaml.tmpl
  embedded-files/serving/seldon_sklearn.yaml.tmpl
  embedded-files/tekton/fuseml.yaml
  examples/mlflow-model/conda.yaml
  paas/client.go
  scripts/seldon-operator-install.sh
Labels: area/blueprint, area/core, in progress

#49 docs: Add Contributing guide
  CONTRIBUTING.md
Labels: area/docs, good first issue, help wanted, in progress

#50 docs: Add Code of Conduct
  CODE_OF_CONDUCT.md
Labels: good first issue, help wanted, in progress

#47 refactor: Wait for the pipeline to succeed
  embedded-files/tekton/fuseml.yaml
  go.mod
  go.sum
  kubernetes/cluster.go
  paas/client.go
Labels: area/core, in progress

#38 tests: Test the inference service
  acceptance/acceptance_suite_test.go
  acceptance/mlflow_test.go
  deployments/tekton.go
  embedded-files/serving/deployment.yaml.tmpl
  embedded-files/serving/kfserving.yaml.tmpl
  embedded-files/serving/seldon_mlflow.yaml.tmpl
  embedded-files/serving/seldon_sklearn.yaml.tmpl
  paas/client.go
Labels: area/ci, in progress
