Repository fuseml/fuseml, pull requests merged in 2021-11, with the labels that each got.

#293 ci: Added a path to test Seldon-Core with Triton based workflow
  .github/workflows/ci.yml
  Makefile
  scripts/ci/mlflow-e2e.sh
Labels: needs-backport

#297 Fix image release action
  .github/workflows/ci.yml
  .github/workflows/release.yml
  Dockerfile
Labels: needs-backport

#301 [0.3] ci: Added a path to test Seldon-Core with Triton based workflow
  .github/workflows/ci.yml
  Makefile
  scripts/ci/mlflow-e2e.sh
Labels: area/ci, backport from main

#303 [0.3] ci: Run tests before creating a release
  .github/workflows/ci.yml
  .github/workflows/get-fuseml-installer.yml
  .github/workflows/release.yml
  scripts/ci/mlflow-e2e.sh
Labels: backport from main

#305 [0.3] ci: don't test the installer twice on release
  .github/workflows/get-fuseml-installer.yml
Labels: backport from main
